const Memo = document.querySelector(".js-Memo"),
      Memo_Title= Memo.querySelector(".js-Memo_Title"),
      Memo_BTN_List= Memo.querySelector(".js-Memo__Button_list"),
      Memo_btn1= Memo.querySelector(".js-Memo__Button_1"),
      Memo_btn2= Memo.querySelector(".js-Memo__Button_2"),
      Memo_btn3= Memo.querySelector(".js-Memo__Button_3"),
      Memo_area= Memo.querySelector(".js-Memo_contents"),
      MD_converted_result=Memo.querySelector(".js-Memo_MD_Display"),
      MD_div=MD_converted_result.querySelector(".js-Memo_MD__contents");
